# Site settings
title: Liao Hanfu's Blog
author: Liao Hanfu
header-img: img/home-bg.jpg
email: hanfuliao@gmail.com
description: "I Leo, I learn and I love."
url: "http://hanfu.space"
twitter_username: lhf_leo
github_username: lhf-leo
facebook_username:  lhf.leo
host: localhost
gems: [jekyll-paginate, jekyll-gist]

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

#Default post settings
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" 
    values:
      layout: post
      category: Learning
      tags: false
      show_excerpt: true
      comments: true

